import re
import requests 

url = "https://api.github.com/emojis"
dirname = "../"
fname = "emoji.lua"
path = dirname + fname


# reg_name = re.compile(r'[^"].*?[^"]')
reg_unicode = re.compile(r'(?<=unicode/)(.*)(?=.png)')

json = requests.get(url).json()

dic = {}
for name, url in json.items():
    match = reg_unicode.search(url)
    if match:
        unicode = match.group(0)
    try:
        int(unicode,16)
        dic[name] = r"\u{"+unicode+"}"
    except ValueError:
        val = ""
        for code in unicode.split("-"):
            val += r"\u{"+code+"}"
        dic[name] = val

with open(path, "w") as f:
    f.write("local emojis = {\n")
    for name, val in dic.items():
        f.write(f'["{name}"]="{val}",\n')
    f.write("}\n")

with open(path, "a") as f:
    s = """\n
local function emoji(str)
local start = 1
local last = -1
if str:sub(1, 1) == ":" then
    start = start + 1
end
if str:sub(-1) ==  ":" then
    last = last - 1
end
    return emojis[str:sub(start, last)]
end

local module = {emojis=emojis, emoji=emoji}

return module



-- this lua module is generated by python script written by tooosay(https://github.com/tooosay)
-- there are no limitation and/or warrantary for this lua code/module.
-- license: public domain. see https://creativecommons.org/publicdomain/zero/1.0/
"""
    f.write(s)







# this python code is written by tooosay(github.com/tooosay).
# license: public domain. see https://creativecommons.org/